### ISSUE TITLE
Instantiations

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#1]
The template instantiations in `Grid/qcd/action/fermion/instantiation/SpWilson*` completely duplicate the structure in `Grid/qcd/action/fermion/instantiation/Wilson*` except for the `#define IMPLEMENTATION ...` line in `*/impl.h`. This is streamlined for the procedure in `scripts/filelist` and might be justified in that respect. We should compare with the other instantiations in that folder and check if the impact on the build scripts is justifiable in favour of a reduction of code duplication.

**Comment by edbennett** [comment]
Worth noting that all of this duplication is (or should be) automatically generated from the `generate_instantiations.sh`. I'm not sure why that is done manually and the results committed rather than being done as part of `bootstrap.sh` though.

**Comment by chillenzer** [comment]
Good point! But `grep -r generate_instantiations .` only finds something in `.git`, so this doesn't seem to be automatically used by now. We should probably ask Peter about the rationale behind all this?

**Comment by edbennett** [comment]
Yes, that's what I meant by my second sentence. It's weird, but potentially not worth rocking the boat over unless we have other related questions that we can ask together.

**Comment by chillenzer** [comment]
Yes, definitely not the one thing to schedule a meeting for but probably something we should bring up when we have one anyways.
