### ISSUE TITLE
Consistent use of N_colour and N_sp in interfaces

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#11]
We should strive for maximal consistency about the use of N_colour and N_sp in the interfaces, particularly when given as a (template) argument for instantiations / initialisation. I suspect that exposing N_colour = 2 N_sp as the interface will save us a bit of trouble for the unification with SU(N).

**Comment by LupoA** [comment]
Done the changes, but I'll commit and close together with at least #3. Had to revert some things because I didn't realise they are related!
