### ISSUE TITLE
Make Group a template parameter in Grid/qcd/action/gauge/GaugeImplTypes.h

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#2]
As the title says...

**Comment by LupoA** [comment]
This applies to all the following 

qcd/action/gauge/GaugeImplTypes.h
qcd/representations/two_index.h
qcd/representations/adjoint.h
qcd/representations/fundamental.h
qcd/utils/SUnTwoIndex.h
qcd/utils/SUnAdjoint.h
qcd/utils/GaugeFix.h

**Comment by LupoA** [comment]
there's then overlaps with #3 and #4
