### ISSUE TITLE
`tests/forces/Test_gpwilson_force.cc` fails for Nc==4

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#23]
This is true for the most recent commit in #22 but seems to go back way earlier (maybe not even on us). Is that expected?

**Comment by LupoA** [comment]
I don't think it is expected, but I know too little to really say. I have never compiled with gparity enabled so I wouldn't have noticed if we broke it.

**Comment by chillenzer** [comment]
That's kind of the thing. I didn't set any such compilation flag (which might be the problem). I will have a look at it.
