### ISSUE TITLE
Add documentation about `--shm` error

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#31]
The resolution of my `--shm` error was that I was parallelising the wrong axes, i.e., I was doing `--mpi=1.1.2.2` instead of `--mpi=2.2.1.1`. While that seems stupid in hindsight, I somehow still thought that this could be a good idea at that time. So, I feel that we should guard against others running into this by, e.g., adding something to the documentation or README or tracking down the error message and adding a hint that it might be a problem of parallelisation.

**Comment by chillenzer** [comment]
PS: The said error message was
```
 ShmBufferMalloc exceeded shared heap size -- try increasing with --shm <MB> flag
 Parameter specified in units of MB (megabytes) 
 Current alloc is 192MB
 Current bytes is 1152MB
 Current heap  is 1024MB
```

**Comment by LupoA** [comment]
what was the global volume of the lattice? (the --grid command)

**Comment by chillenzer** [comment]
It was `Benchmark_ITT` right after
```
Grid : Message : 21.362239 s : ==================================================================================
Grid : Message : 21.550668 s : ==================================================================================
Grid : Message : 21.550701 s : Benchmark DWF on 32^4 local volume 
Grid : Message : 21.550703 s : * Nc             : 4
Grid : Message : 21.550705 s : * Global volume  : 32 32 64 64 
Grid : Message : 21.550717 s : * Ls             : 12
Grid : Message : 21.550723 s : * ranks          : 4
Grid : Message : 21.550725 s : * nodes          : 1
Grid : Message : 21.550726 s : * ranks/node     : 4
Grid : Message : 21.550728 s : * ranks geom     : 1 1 2 2 
Grid : Message : 21.550731 s : * Using 4 threads
Grid : Message : 21.550732 s : ==================================================================================
Grid : Message : 24.469923 s : Initialised RNGs
```

**Comment by chillenzer** [comment]
Discussed with Alessandro on Friday: We should open a corresponding issue on Peter's repo.

**Comment by chillenzer** [comment]
PS: https://github.com/paboyle/Grid/issues/438#issue-1762255092
