### ISSUE TITLE
Force computation on GPU for Antisymmetric Representation

### ISSUE THREAD

**Issue by chillenzer** [LupoA/Grid#8]
There seems to be an issue with this. Ed can fill in the details here...

**Comment by edbennett** [comment]
When running HMC (or RHMC) with two-index antisymmetric fermions on GPU, the output for the average force is precisely zero. Specifically, we see lines in the output like:

```
Grid : Integrator : 77.493420 s : Hirep Force average: 0
```

We need to investigate:

1. Is this just a problem with output or does it also affect the physics?
2. What is causing it? (If it's the output, then why is the value not being set correctly; if it is the computation, then where should the computation be occurring and why isn't it?)
3. How should it be fixed?

The first two can probably be done concurrently, with the help of a debugger, and may not require as deep an understanding of the code as other aspects of the work, so I thought this might be something for Niccolò (whose username I don't know so I can't tag him) to look at independently.

**Comment by edbennett** [comment]
For completeness: this appears specific to the 2AS representation—the adjoint representation I'm using on another project gives a correct computation here
